# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateAnimalInformation.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 251, 16))
        self.label.setObjectName("label")
        self.healthBox = QtWidgets.QComboBox(self.centralwidget)
        self.healthBox.setGeometry(QtCore.QRect(30, 250, 181, 22))
        self.healthBox.setObjectName("healthBox")
        self.healthBox.addItem("")
        self.healthBox.addItem("")
        self.healthBox.addItem("")
        self.animaltypeBox = QtWidgets.QComboBox(self.centralwidget)
        self.animaltypeBox.setGeometry(QtCore.QRect(30, 70, 181, 22))
        self.animaltypeBox.setObjectName("animaltypeBox")
        self.animaltypeBox.addItem("")
        self.animaltypeBox.addItem("")
        self.animaltypeBox.addItem("")
        self.animaltypeBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 101, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 190, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.genderBox = QtWidgets.QComboBox(self.centralwidget)
        self.genderBox.setGeometry(QtCore.QRect(30, 130, 181, 22))
        self.genderBox.setObjectName("genderBox")
        self.genderBox.addItem("")
        self.genderBox.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(310, 220, 181, 31))
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 170, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.label_6.setObjectName("label_6")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(310, 50, 181, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 260, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 300, 171, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 21))
        self.menubar.setObjectName("menubar")
        self.menuUpdate_Information = QtWidgets.QMenu(self.menubar)
        self.menuUpdate_Information.setObjectName("menuUpdate_Information")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuUpdate_Information.addSeparator()
        self.menubar.addAction(self.menuUpdate_Information.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Filter for the exact animal you want to view or edit:"))
        self.healthBox.setItemText(0, _translate("MainWindow", "Healthy"))
        self.healthBox.setItemText(1, _translate("MainWindow", "Sick"))
        self.healthBox.setItemText(2, _translate("MainWindow", "Pregnant"))
        self.animaltypeBox.setItemText(0, _translate("MainWindow", "Cow"))
        self.animaltypeBox.setItemText(1, _translate("MainWindow", "Chicken"))
        self.animaltypeBox.setItemText(2, _translate("MainWindow", "Goat"))
        self.animaltypeBox.setItemText(3, _translate("MainWindow", "Sheep"))
        self.label_4.setText(_translate("MainWindow", "Health State:"))
        self.label_3.setText(_translate("MainWindow", "Gender:"))
        self.genderBox.setItemText(0, _translate("MainWindow", "Male"))
        self.genderBox.setItemText(1, _translate("MainWindow", "Female"))
        self.label_5.setText(_translate("MainWindow", "Color:"))
        self.label_6.setText(_translate("MainWindow", "Animal Type:"))
        self.pushButton.setText(_translate("MainWindow", "Select Animal"))
        self.pushButton_2.setText(_translate("MainWindow", "Next Animal"))
        self.pushButton_3.setText(_translate("MainWindow", "Save New Animal Information"))
        self.menuUpdate_Information.setTitle(_translate("MainWindow", "Update Information"))

